### ISSUE TITLE
Add Support for Multiple Themes

### ISSUE THREAD

**Issue by pratyush090506** [Alitindrawan24/Binary-Calculator#96] opened 2024-10-13 19:45 UTC

**Comment by Alitindrawan24** [comment] 2024-10-15 01:31
What kind theme would you add ?

**Comment by allanoguis** [comment] 2024-10-15 01:39
we can add a theme switcher for multiple themes with or without tailwind but we have to refactor some css

**Comment by Alitindrawan24** [comment] 2024-10-15 01:41
@allanoguis is that takes big effort and impact big changes in code ?

**Comment by allanoguis** [comment] 2024-10-15 01:44
it would have an impact on the developer experience. it may require a huge refactor since it's been coded raw on CSS. but once properly setup, you can apply as many themes as you want.

**Comment by Alitindrawan24** [comment] 2024-10-15 01:46
Interesting, I will assign it to you @allanoguis

**Comment by allanoguis** [comment] 2024-10-15 01:48
thanks @Alitindrawan24

**Comment by allanoguis** [comment] 2024-10-15 03:06
@Alitindrawan24  i have 1 concern though. I will add at least 1 theme so that would make 3. the problem is the darkmode button. should i leave it and add buttons somewhere on the page? 
![image](https://github.com/user-attachments/assets/d80921a0-95f1-4101-b9d5-b41b5ffcb37f)

**Comment by Alitindrawan24** [comment] 2024-10-15 05:40
@allanoguis yes that is great idea

**Comment by allanoguis** [comment] 2024-10-15 07:51
@Alitindrawan24 i am almost done with the color themes. please give me 2 hours or so. I have seen alot of css duplicates and weird html tags. rest assured that it did not break the calculator engine. here's how it's going so far:

![image](https://github.com/user-attachments/assets/752a29bb-00fa-4bec-929f-9ef0f50a4f72)

![image](https://github.com/user-attachments/assets/d416aa87-4688-4230-9b3d-c1745b133385)

i disabled the moon button, you can choose whatever button you want in the future but for now i'll make everything work and clean.

**Comment by allanoguis** [comment] 2024-10-15 07:52
the button styling will follow after these tests. so far so good.

**Comment by allanoguis** [comment] 2024-10-15 11:12
Hello @Alitindrawan24 I'm sorry for the recent PR but I think I have the updated files on my end. I have synced the files here and completed consolidating the merges. please see before I proceed.

![image](https://github.com/user-attachments/assets/ed01a645-f531-4393-adfa-59f36de16b5f)

As you can see here, I have the updated factorial and Square button. I can fix this layout before updating my PR.

This is the plan:

![image](https://github.com/user-attachments/assets/80cf1ba8-9b11-46a9-87d8-ea0a1cdc8de4)

I will remove the dark mode button. replace it with the gray button, and fix the overall layout. 

Awaiting for you reply, thanks

**Comment by Alitindrawan24** [comment] 2024-10-15 12:02
Ok @allanoguis but make sure regularly update the code from Main to prevent conflict

**Closed** 2024-10-15 12:04 UTC
Labels: enhancement, hacktoberfest-accepted, hacktoberfest
